import 'src/components/common/logoBubble/LogoBubble.scss';

import React from 'react';
import defineBlock from 'src/utils/defineBlock';

const bem = defineBlock('LogoBubble');

const LogoBubble = () => (
  <div className={bem()}>
    <svg
      width="312"
      height="313"
      viewBox="0 0 312 313"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g opacity="0.72">
        <g
          opacity="0.5"
          filter="url(#filter0_f_1_469)"
        >
          <circle
            cx="124.879"
            cy="124.879"
            r="44.8789"
            fill="#CB8F8F"
          />
        </g>
        <g filter="url(#filter1_bi_1_469)">
          <circle
            cx="195.817"
            cy="195.817"
            r="115.817"
            fill="#C4C4C4"
            fill-opacity="0.01"
          />
        </g>
        <circle
          cx="195.817"
          cy="195.817"
          r="115.317"
          stroke="url(#paint0_linear_1_469)"
        />
        <g
          opacity="0.7"
          filter="url(#filter2_f_1_469)"
        >
          <ellipse
            cx="156.393"
            cy="144.811"
            rx="15.9044"
            ry="26.6158"
            transform="rotate(45 156.393 144.811)"
            fill="#FF9BC5"
            fill-opacity="0.2"
          />
        </g>
        <g
          opacity="0.35"
          filter="url(#filter3_f_1_469)"
        >
          <ellipse
            cx="254.984"
            cy="263.671"
            rx="15.369"
            ry="31.4544"
            transform="rotate(45 254.984 263.671)"
            fill="#DF9BFF"
          />
        </g>
        <g filter="url(#filter4_f_1_469)">
          <path
            d="M166.862 85.1448C129.411 94.9156 99.4366 123.194 87.2928 159.624H87.2385V155.424C100.337 120.228 130.06 93.121 166.862 83.6488V85.1448Z"
            fill="#DFB9D7"
          />
        </g>
        <g filter="url(#filter5_f_1_469)">
          <ellipse
            cx="119.211"
            cy="110.488"
            rx="17.3725"
            ry="4.34312"
            transform="rotate(-40.3806 119.211 110.488)"
            fill="#AED4D2"
          />
        </g>
        <g filter="url(#filter6_f_1_469)">
          <ellipse
            cx="119.211"
            cy="110.488"
            rx="13.6395"
            ry="6.58492"
            transform="rotate(-40.3806 119.211 110.488)"
            fill="white"
            fill-opacity="0.1"
          />
        </g>
      </g>
      <defs>
        <filter
          id="filter0_f_1_469"
          x="0"
          y="0"
          width="249.758"
          height="249.758"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="40"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <filter
          id="filter1_bi_1_469"
          x="60"
          y="60"
          width="271.633"
          height="271.633"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feGaussianBlur
            in="BackgroundImageFix"
            stdDeviation="10"
          />
          <feComposite
            in2="SourceAlpha"
            operator="in"
            result="effect1_backgroundBlur_1_469"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_backgroundBlur_1_469"
            result="shape"
          />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset
            dx="-4"
            dy="-4"
          />
          <feGaussianBlur stdDeviation="8" />
          <feComposite
            in2="hardAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
          />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.751506 0 0 0 0 0.608333 0 0 0 0 1 0 0 0 1 0"
          />
          <feBlend
            mode="normal"
            in2="shape"
            result="effect2_innerShadow_1_469"
          />
        </filter>
        <filter
          id="filter2_f_1_469"
          x="110.465"
          y="98.8838"
          width="91.8553"
          height="91.8553"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="12"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <filter
          id="filter3_f_1_469"
          x="206.224"
          y="214.91"
          width="97.5205"
          height="97.5206"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="12"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <filter
          id="filter4_f_1_469"
          x="75.2385"
          y="71.6488"
          width="103.624"
          height="99.9752"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="6"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <filter
          id="filter5_f_1_469"
          x="84.6785"
          y="77.7539"
          width="69.0645"
          height="65.4684"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="10.5"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <filter
          id="filter6_f_1_469"
          x="91.976"
          y="84.3257"
          width="54.4693"
          height="52.3254"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="8"
            result="effect1_foregroundBlur_1_469"
          />
        </filter>
        <linearGradient
          id="paint0_linear_1_469"
          x1="80"
          y1="80"
          x2="311.633"
          y2="311.633"
          gradientUnits="userSpaceOnUse"
        >
          <stop stop-color="#F9E5B2" />
          <stop
            offset="1"
            stop-color="#640DFB"
            stop-opacity="0.1"
          />
        </linearGradient>
      </defs>
    </svg>
    <svg
      width="381"
      height="515"
      viewBox="0 0 381 515"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g
        opacity="0.5"
        filter="url(#filter0_f_1_335)"
      >
        <circle
          cx="134.637"
          cy="162.462"
          r="54.6375"
          fill="#CB8F8F"
        />
      </g>
      <g filter="url(#filter1_f_1_335)">
        <circle
          cx="221"
          cy="354.575"
          r="91.65"
          fill="#240E74"
        />
      </g>
      <g filter="url(#filter2_f_1_335)">
        <circle
          cx="221"
          cy="153.65"
          r="91.65"
          fill="#55108B"
        />
      </g>
      <g
        opacity="0.7"
        filter="url(#filter3_i_1_335)"
      >
        <circle
          cx="221"
          cy="248.825"
          r="141"
          fill="#C4C4C4"
          fill-opacity="0.01"
        />
      </g>
      <g filter="url(#filter4_bi_1_335)">
        <circle
          cx="221"
          cy="248.825"
          r="141"
          fill="#C4C4C4"
          fill-opacity="0.01"
        />
      </g>
      <circle
        cx="221"
        cy="248.825"
        r="140.5"
        stroke="url(#paint0_linear_1_335)"
      />
      <g filter="url(#filter5_f_1_335)">
        <circle
          cx="221"
          cy="248.825"
          r="138"
          stroke="url(#paint1_linear_1_335)"
          stroke-width="6"
        />
        <circle
          cx="221"
          cy="248.825"
          r="138"
          stroke="black"
          stroke-opacity="0.2"
          stroke-width="6"
        />
      </g>
      <g
        opacity="0.3"
        filter="url(#filter6_i_1_335)"
      >
        <circle
          cx="221"
          cy="248.825"
          r="141"
          fill="#C4C4C4"
          fill-opacity="0.01"
        />
      </g>
      <circle
        cx="221"
        cy="248.825"
        r="140.5"
        stroke="url(#paint2_linear_1_335)"
      />
      <g
        opacity="0.7"
        filter="url(#filter7_f_1_335)"
      >
        <ellipse
          cx="173.004"
          cy="186.729"
          rx="19.3627"
          ry="32.4032"
          transform="rotate(45 173.004 186.729)"
          fill="#FF9BC5"
        />
      </g>
      <g
        opacity="0.35"
        filter="url(#filter8_f_1_335)"
      >
        <ellipse
          cx="293.034"
          cy="331.434"
          rx="18.7109"
          ry="38.294"
          transform="rotate(45 293.034 331.434)"
          fill="#DF9BFF"
        />
      </g>
      <g filter="url(#filter9_f_1_335)">
        <path
          d="M185.75 114.088C140.155 125.984 103.663 160.41 88.8786 204.762H88.8125V199.649C104.76 156.8 140.945 123.799 185.75 112.267V114.088Z"
          fill="#DFB9D7"
        />
      </g>
      <g filter="url(#filter10_f_1_335)">
        <ellipse
          cx="127.737"
          cy="144.942"
          rx="21.15"
          ry="5.2875"
          transform="rotate(-40.3806 127.737 144.942)"
          fill="#D4AEBD"
        />
      </g>
      <g
        opacity="0.7"
        filter="url(#filter11_f_1_335)"
      >
        <ellipse
          cx="127.737"
          cy="144.943"
          rx="47.6783"
          ry="11.9196"
          transform="rotate(-40.3806 127.737 144.943)"
          fill="#D4AEBD"
        />
      </g>
      <g filter="url(#filter12_f_1_335)">
        <ellipse
          cx="312.799"
          cy="354.68"
          rx="21.15"
          ry="5.2875"
          transform="rotate(-40.3806 312.799 354.68)"
          fill="#A08FF4"
        />
      </g>
      <g filter="url(#filter13_f_1_335)">
        <ellipse
          cx="127.737"
          cy="144.943"
          rx="16.6053"
          ry="8.01676"
          transform="rotate(-40.3806 127.737 144.943)"
          fill="white"
        />
      </g>
      <defs>
        <filter
          id="filter0_f_1_335"
          x="0"
          y="27.825"
          width="269.275"
          height="269.275"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="40"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter1_f_1_335"
          x="61.35"
          y="194.925"
          width="319.3"
          height="319.3"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="34"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter2_f_1_335"
          x="67.35"
          y="0"
          width="307.3"
          height="307.3"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="31"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter3_i_1_335"
          x="56"
          y="83.8251"
          width="306"
          height="306"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset
            dx="-24"
            dy="-24"
          />
          <feGaussianBlur stdDeviation="27" />
          <feComposite
            in2="hardAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
          />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.3155 0 0 0 0 0.075 0 0 0 0 1 0 0 0 1 0"
          />
          <feBlend
            mode="normal"
            in2="shape"
            result="effect1_innerShadow_1_335"
          />
        </filter>
        <filter
          id="filter4_bi_1_335"
          x="60"
          y="87.8251"
          width="322"
          height="322"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feGaussianBlur
            in="BackgroundImageFix"
            stdDeviation="10"
          />
          <feComposite
            in2="SourceAlpha"
            operator="in"
            result="effect1_backgroundBlur_1_335"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_backgroundBlur_1_335"
            result="shape"
          />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset
            dx="-4"
            dy="-4"
          />
          <feGaussianBlur stdDeviation="8" />
          <feComposite
            in2="hardAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
          />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.751506 0 0 0 0 0.608333 0 0 0 0 1 0 0 0 1 0"
          />
          <feBlend
            mode="normal"
            in2="shape"
            result="effect2_innerShadow_1_335"
          />
        </filter>
        <filter
          id="filter5_f_1_335"
          x="64"
          y="91.8251"
          width="314"
          height="314"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="8"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter6_i_1_335"
          x="80"
          y="107.825"
          width="285"
          height="285"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset
            dx="3"
            dy="3"
          />
          <feGaussianBlur stdDeviation="2" />
          <feComposite
            in2="hardAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
          />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"
          />
          <feBlend
            mode="normal"
            in2="shape"
            result="effect1_innerShadow_1_335"
          />
        </filter>
        <filter
          id="filter7_f_1_335"
          x="122.308"
          y="136.033"
          width="101.391"
          height="101.391"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="12"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter8_f_1_335"
          x="238.889"
          y="277.289"
          width="108.288"
          height="108.288"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="12"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter9_f_1_335"
          x="76.8125"
          y="100.267"
          width="120.938"
          height="116.495"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="6"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter10_f_1_335"
          x="90.2621"
          y="109.657"
          width="74.9494"
          height="70.5714"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="10.5"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter11_f_1_335"
          x="58.5979"
          y="80.7384"
          width="138.278"
          height="128.408"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="16"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter12_f_1_335"
          x="281.325"
          y="325.394"
          width="62.9495"
          height="58.5714"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="7.5"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <filter
          id="filter13_f_1_335"
          x="98.0592"
          y="116.57"
          width="59.3551"
          height="56.7451"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood
            flood-opacity="0"
            result="BackgroundImageFix"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="8"
            result="effect1_foregroundBlur_1_335"
          />
        </filter>
        <linearGradient
          id="paint0_linear_1_335"
          x1="80"
          y1="107.825"
          x2="362"
          y2="389.825"
          gradientUnits="userSpaceOnUse"
        >
          <stop stop-color="#640DFB" />
          <stop
            offset="0.755208"
            stop-color="#640DFB"
            stop-opacity="0.1"
          />
        </linearGradient>
        <linearGradient
          id="paint1_linear_1_335"
          x1="119.48"
          y1="147.305"
          x2="322.52"
          y2="350.345"
          gradientUnits="userSpaceOnUse"
        >
          <stop stop-color="#FF9179" />
          <stop
            offset="0.255208"
            stop-color="#FF5CF0"
          />
          <stop
            offset="0.541667"
            stop-color="#8466FF"
          />
          <stop
            offset="1"
            stop-color="#002FA8"
          />
        </linearGradient>
        <linearGradient
          id="paint2_linear_1_335"
          x1="80"
          y1="107.825"
          x2="362"
          y2="389.825"
          gradientUnits="userSpaceOnUse"
        >
          <stop stop-color="#F9E5B2" />
          <stop
            offset="1"
            stop-color="#640DFB"
            stop-opacity="0.1"
          />
        </linearGradient>
      </defs>
    </svg>
  </div>
);

export default LogoBubble;
